import random

# dice has 6 sides
NUM_SIDES = 6  

# roll the dice random number between 1 and 6 generated by random.randint and add them together.
# die1 and die2 are local variables and their scope is limited to the roll_dice function.
def roll_dice():
    die1 = random.randint(1, NUM_SIDES)  
    die2 = random.randint(1, NUM_SIDES)  
    total = die1 + die2  
    print(f"Die 1: {die1}, Die 2: {die2} → Total: {total}")



# call roll_dice function and print the result.
# die1 variable is defined in scope of main function and it is not the same as die1 in roll_dice function
# its a local variable and its accessible only in main function.
def main():
    die1 = 10    
    print(f"die1 in main() starts as: {die1}")

    # roll the dice 3 times
    for _ in range(3):
        roll_dice()

    print(f"die1 in main() is still: {die1}")  

if __name__ == '__main__':
    main()